/**
 * File generated by Magnet rest2mobile 1.1 - 21/05/2016 11:56:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.hack.cooltivar.r2m.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import java.util.List;

public class TemperatureTakerFactory extends ControllerFactory<TemperatureTaker> {
  public TemperatureTakerFactory(MagnetMobileClient magnetClient) {
    super(TemperatureTaker.class, TemperatureTakerSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller TemperatureTaker
  public static class TemperatureTakerSchemaFactory extends AbstractControllerSchemaFactory {
    private static TemperatureTakerSchemaFactory __instance;

    public static synchronized TemperatureTakerSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new TemperatureTakerSchemaFactory();
      }

      return __instance;
    }

    private TemperatureTakerSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method takeTemperatureValue
      JMethod method1 = addMethod("takeTemperatureValue",
        "044a7f4b43fa42f19ba577af3fb21918/pin/V1",
        "GET",
        List.class,
        String.class,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://192.168.1.133:8070");
    }

  }

}
