/**
 * File generated by Magnet rest2mobile 1.1 - 21/05/2016 11:56:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.hack.cooltivar.r2m.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import java.util.List;

public interface TemperatureTaker {

  /**
   * Generated from URL GET http://192.168.1.133:8070/044a7f4b43fa42f19ba577af3fb21918/pin/V1
   * GET 044a7f4b43fa42f19ba577af3fb21918/pin/V1
   * @param listener
   * @return List<java.lang.String>
   */
  Call<List<java.lang.String>> takeTemperatureValue(StateChangedListener listener);
}
