/**
 * File generated by Magnet rest2mobile 1.1 - 21/05/2016 11:56:20 PM
 * @see {@link http://developer.magnet.com}
 */

package com.hack.cooltivar.r2m.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.hack.cooltivar.r2m.controller.api.TemperatureTaker;
import com.hack.cooltivar.r2m.controller.api.TemperatureTakerFactory;
import java.util.List;

/**
* This is generated stub to test {@link TemperatureTaker}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class TemperatureTakerTest extends InstrumentationTestCase {
  private TemperatureTaker temperatureTaker;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    TemperatureTakerFactory controllerFactory = new TemperatureTakerFactory(magnetClient);
    temperatureTaker = controllerFactory.obtainInstance();

    assertNotNull(temperatureTaker);
  }

  /**
    * Generated unit test for {@link TemperatureTaker#takeTemperatureValue}
    */
  @SmallTest
  public void testTakeTemperatureValue() throws SchemaException, ExecutionException, InterruptedException {
    Call<List<java.lang.String>> callObject = temperatureTaker.takeTemperatureValue(null);
    assertNotNull(callObject);

    List<java.lang.String> result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
